### ISSUE TITLE
found API keys in source code

### ISSUE THREAD

**Issue by shao1555** [popshootjapan/WeiWallet-iOS#3]
ref: https://github.com/popshootjapan/WeiWallet-iOS/blame/master/Wei/Utility/Environment.swift#L48-L59

For safety of products, I think that these keys should not be included in the source code.

**Comment by yuzushioh** [comment]
Hi @shao1555, Thank you for the report. 
We talked about this before we released as an oss. Since Metamask, MEW, and Trust includes etherscan api key and infura's endpoint, we decided to do the same. It makes it easier for devs to set up the project. And it would not affect the application itself even if the keys are revealed (It would if someone tried to attack the node or etherscan).
